### PR TITLE
Added Security Misconfiguration to Security

### PR DESCRIPTION
**Pull request by svavadogg**

### CODE REVIEW

**Comment by danielbsig** [comment]
Seems to be quite similar to https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration, we should at least add a link to that page at the top of this section and quote the relevant paragraphs.

**Comment by svavadogg** [comment]
Já auðvitað!
Ég laga þetta og geri nýtt púkk request :)

Bestu kveðjur,
Svava Dögg

On 16 Nov 2016, at 09:36, Daníel B. Sigurgeirsson <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems to be quite similar to https://www.owasp.org/index.php/Top_10_2013-A5-Security_Misconfiguration, we should at least add a link to that page at the top of this section and quote the relevant paragraphs.

##

**Comment by svavadogg** [comment]
Fixed!

**Comment by svavadogg** [comment]
svava13@ru.is

**Comment by danielbsig** [comment]
75/100

**Pull request merged**
